name: Add Workspace Role Assignment

on:
  workflow_dispatch:
    inputs:
      WorkspaceID:
        description: 'ID of Workspace'
        required: true
        type: string
      Permission:
        description: 'Permission in Workspace'
        required: true
        type: string
      ID:
        description: 'ID of User/Group'
        required: true
        type: string
      Type_ID:
        description: 'Type of ID'
        required: true
        type: string

jobs:
  runAPI:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FBTOKEN }}
    steps:
      - name: Add Workspace Role Assignment
        id: create_ws
        run: |
          ws_api_create="$(gh api -X POST POST https://api.fabric.microsoft.com/v1/workspaces/${{ inputs.WorkspaceID }}/roleAssignments -f body='
          {
            "principal": {
            "id": ${{ inputs.ID }},
            "type": ${{ inputs.Type_ID }}
            },
            "role": ${{ inputs.Permission }}
          } \
          --header  "Content-Type":"application/json" \
          --header  "Authorization":"Bearer ${{ secrets.FBTOKEN }}")"

