name: Create a Fabric Workspace

on:
  workflow_dispatch:
    inputs:
      workspacename:
        description: 'Name of the Workspace'
        required: true
        type: string
jobs:
  runAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Create a Fabric Workspace
        run: |
          gh api -X POST https://api.fabric.microsoft.com/v1/workspaces -f body='
          {
            "displayName": ${{ inputs.workspacename }} 
          }'
