name: Create a Fabric Workspace

on:
  workflow_dispatch:
    inputs:
      workspacename:
        description: 'Name of Workspace'
        required: true
        type: string

jobs:
  runAPI:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FBTOKEN }}
    steps:
      - name: Create a Fabric Workspace
        run: |
          gh api -X POST https://api.fabric.microsoft.com/v1/workspaces -f displayName="${{ inputs.workspacename }}" \
          --header  "Content-Type":"application/json" \
          --header  "Authorization":"Bearer ${{ secrets.FBTOKEN }}" >> $GITHUB_OUTPUT
    
      - name: Get Fabric Workspace ID
        run: 
          echo >> $GITHUB_OUTPUT
