name: Create a Fabric Workspace

on:
  workflow_dispatch:
    inputs:
      workspacename:
        description: 'Name of Workspace'
        required: true
        type: string

jobs:
  runAPI:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FBTOKEN }}
    steps:
      - name: Create a Fabric Workspace
        id: create_ws
        run: |
          gh api -X POST https://api.fabric.microsoft.com/v1/workspaces -f displayName="${{ inputs.workspacename }}" --jq '.[].id' \
          --header  "Content-Type":"application/json" \
          --header  "Authorization":"Bearer ${{ secrets.FBTOKEN }}"
    
      - name: Get Fabric Workspace ID
        env:
          WS_ID: ${{ toJson(steps.create_ws.outputs) }}  
        run:
          echo ${{ env.WS_ID }}  
